---
- name: Configure EC2 Server
  hosts: webservers
  become: yes

  vars:
    app_name: Karthik DevOps Portfolio
    app_environment: production

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - nginx
          - docker.io
          - git
        state: present

    - name: Start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    
